### ISSUE TITLE
can you share the trained model? 

### ISSUE THREAD

**Issue by helxsz** [experiencor/image-to-3d-bbox#1]
is it possible for you to share the trained model?

**Comment by experiencor** [comment]
Sorry for the late reply. I was traveling last few days. Do you still need it?

**Comment by helxsz** [comment]
@experiencor , It will be great if you can share it, so I want to try first and train it as well.

**Comment by experiencor** [comment]
@helxsz This is the weights to regress the orientation of the car from the image patch defined by the respective 2D bounding box [https://1drv.ms/u/s!ApXgmQqTQot_hWWR4RDORU9jsxRP](https://1drv.ms/u/s!ApXgmQqTQot_hWWR4RDORU9jsxRP). I don't have enough time to clean the code but please let me know if you are stuck at somewhere.
