### ISSUE TITLE
'range' error happens, probably python version unmatched.

### ISSUE THREAD

**Issue by jkstyle2** [experiencor/image-to-3d-bbox#15]
Hi,
When I try the model to learn using model.fit_generator() , as the code written, there happens type error as following: 

> <ipython-input-2-51f3a64f3ada> in data_gen(all_objs, batch_size)
>     129 
>     130     keys = range(num_obj)
> --> 131     np.random.shuffle(keys)
>     132 
>     133     l_bound = 0
> 
> mtrand.pyx in mtrand.RandomState.shuffle()
> 
> mtrand.pyx in mtrand.RandomState.shuffle()
> 
> TypeError: 'range' object does not support item assignment

I'm not very sure of it, but it seems the python version is different from what you uses.
I'm currently using python3.5. Which version of python are you using? or is this from other issue?

Thanks in advance.

**Comment by chaharhimanshu** [comment]
Do you find a solution?
