### ISSUE TITLE
Regress 3D boxes on a video problem

### ISSUE THREAD

**Issue by jediofgever** [experiencor/image-to-3d-bbox#3]
Hello, 
So I am trying to run the code, I have downloaded related kitti dataset and after running of 20 epochs it is throwing an error and it says there is no files in `box_3d` and `box_2d`. Indeed when I chech there is not even such folders in ` 2011_09_26/2011_09_26_drive_0009_sync` directory. My issue is how to get this txt files, Can you provide me the link ?

Thank you very much

**Comment by experiencor** [comment]
@jediofgever Here you go https://1drv.ms/u/s!ApLdDEW3ut5fgQIjeiYqzKFNkfxe!

**Comment by jediofgever** [comment]
@experiencor  Thank you very much!. Did you label this by yourself ? I couldnt see this labels anywhere in KITTI dataset

**Comment by experiencor** [comment]
@jediofgever I infer them from the KITTI labels.

**Comment by jediofgever** [comment]
@experiencor  so after a litlle effort I could successfully run the first file `3D Box Regression.ipynb ` Now I see some directories in the second file `Final KITTI Evaluation.ipynb` such as ;
```
predict_dir = '/home/husky/github/vehicle-detector/2011_09_26/2011_09_26_drive_0009_sync/predict_02/'
calib_dir = '/home/husky/github/vehicle-detector/2011_09_26/2011_09_26_drive_0009_sync/calib_02/'
label_dir = '/home/husky/github/vehicle-detector/2011_09_26/2011_09_26_drive_0009_sync/label_02/'

```
But I don't hold this files and I cannot find them in kitti dataset as well 
May I ask how did you get this files ? Alsi inferred from Kitti?  if so Can you please tell me how to do it 
Thank you in advance

**Comment by experiencor** [comment]
These are the missing files: [calib_label_predict.zip](https://github.com/experiencor/image-to-3d-bbox/files/1575660/calib_label_predict.zip).

I don't remember how exactly I infer these files but I rely heavily on their dev kit (http://kitti.is.tue.mpg.de/kitti/devkit_raw_data.zip). You will figure it out from the readme in the dev kit.

**Comment by jkstyle2** [comment]
@jediofgever @experiencor When I checked the label_02 that you uploaded, I found the bounding box size Xmin/max, Ymin/max have 0,0,0,0, which can't be made as a label. Could you please explain what these zero values indicate?
