### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by tanakataiki** [experiencor/image-to-3d-bbox#6]
Thanks for a great work.

I am trying to use test this code but 
python2.7 tensorflow0.9 causes
'module' object has no attribute 'getdlopenflags' 

and
python 3.5 tensorflow1.6 causes error 
'range' object does not support item assignment

So can you tell me your environment please?

**Comment by jkstyle2** [comment]
Hi @tanakataiki , I have a same issue with python 3.5, error: 'range' object does not support item assignment.
Have you solved the issue?
