### ISSUE TITLE
Always predicting same angle

### ISSUE THREAD

**Issue by konnerthg** [experiencor/image-to-3d-bbox#8]
Thank you for your contribution.

I've tried to overfit the model in 32 KITTI images & labels. For simplification I've used the ground truth labels instead of detections for evaluation. Thus, perfect detections are given. After ages of debugging I've come to the conclusion that the model always predicts the same angle:

```
[ 0.999828  -0.0185488]
[ 0.999828   -0.01854841]
[ 0.9998279  -0.01854766]
[ 0.999828   -0.01854596]
[ 0.999828   -0.01854865]
[ 0.9998279  -0.01854849]
[ 0.9998279  -0.01854877]
[ 0.9998279  -0.01854851]
[ 0.999828   -0.01854779]
[ 0.999828  -0.0185478]
[ 0.999828   -0.01854848]
[ 0.999828   -0.01854868]
[ 0.999828   -0.01854851]
[ 0.999828   -0.01854844]
[ 0.999828   -0.01854522]
[ 0.99982804 -0.01854669]
[ 0.999828   -0.01854509]
[ 0.999828   -0.01854768]
[ 0.99982804 -0.01854698]
[ 0.9998279  -0.01854835]
[ 0.999828  -0.0185477]
```

This being the output of 
`anchors = prediction[1][0][max_anc]`

The orientation loss is about -0.95.

Have you ever had this problem? Thank you.

**Comment by jkstyle2** [comment]
@konnerthg  Have you solved the issue?

**Comment by konnerthg** [comment]
@jkstyle2 I have not. I ended up implementing the angle branch myself and it worked.

**Comment by jkstyle2** [comment]
@konnerthg you mean you didn't solve the issue, but you could work it out on your own?

**Comment by konnerthg** [comment]
@jkstyle2 yes. I just tried to reproduce the steps in the paper instead of using this implementation

**Comment by jkstyle2** [comment]
@konnerthg Wow!! Would you please share some codes of yours or provide me a guideline?? I'm new to this area and I've been strugging with it by myself day and night.. T.T..please!!

**Comment by konnerthg** [comment]
I cannot share any details on the implementation, unfortunately. In terms of a guideline, the paper is rather precise about the network architecture. If you are familiar with any deep learning framework, reproducing it should be straightforward. Feel free to email me if there is anything specific you think I can help you with.

**Comment by jkstyle2** [comment]
@konnerthg Thanks for the kind words! I'll contact you after trying to implement it by myself first.

**Comment by jkstyle2** [comment]
@konnerthg Hi, I really need your help. Can you please explain to me how we can calculate the local orientation from kitti's label? The written code here is as below, but I can't understand it at all. I consider we have to just add 3/(2*pi) to the alpha to get the local orientation. Please correct me if I'm wrong.

            new_alpha = float(line[3]) + np.pi / 2.
            if new_alpha < 0:
                new_alpha = new_alpha + 2. * np.pi
            new_alpha = new_alpha - int(new_alpha / (2. * np.pi)) * (2. * np.pi)
